export const practices = [
	{
		name: 'Abbeydale Road Family Dental Centre',
		location: '4-6 Abbeydale Rd, Highfield, Sheffield S7 1FD',
		image: 'abbeydale-road.jpg',
		href: 'abbeydale-road-family-dental-centre',
	},
	{
		name: 'Seven Dental',
		location: '69-75 Radford Road, Hyson Green, Nottingham NG7 5DR',
		image: 'seven-dental.png',
		href: 'seven-dental',
	},
	{
		name: 'Anstey Family Dental Centre',
		location: '9 Bradgate Rd, Anstey, Leicester LE7 7AB',
		image: 'anstey.jpg',
		href: 'anstey-family-dental-centre',
	},
	{
		name: 'Market Place Dental Care',
		location: 'Nottinghamshire',
		image: 'marketplace.png',
		href: 'market-place-dental-care',
	},
	{
		name: 'Clay Cross Family Dental Centre',
		location: 'Chesterfield',
		image: 'clay-cross.jpg',
		href: 'clay-cross-family-dental-centre',
	},
	{
		name: 'Dalton Dental Care',
		location: 'Rotherham',
		image: 'dalton.png',
		href: 'dalton-dental-care',
	},
	{
		name: 'South Elmsall Family Dental Centre',
		location: 'Wakefield',
		image: 'south-elmsall.png',
		href: 'south-elmsall-family-dental-centre',
	},
	{
		name: 'Hillsborough Family Dental Centre',
		location: 'Sheffield',
		image: 'hillsborough.jpg',
		href: 'hillsborough-family-dental-centre',
	},
	{
		name: 'Hoyland Road',
		location: 'Barnsley',
		image: 'hoyland.png',
		href: 'hoyland-road-dental',
	},
	{
		name: 'Portland Road Dental',
		location: 'Hucknall',
		image: 'portland.png',
		href: 'portland-road-dental',
	},
	{
		name: 'Sileby Dental',
		location: 'Leicester',
		image: 'sileby.png',
		href: 'sileby-dental',
	},
	{
		name: 'Sneinton Family Dental',
		location: 'Nottingham',
		image: 'sneinton.jpg',
		href: 'sneinton-family-dental',
	},
	{
		name: 'Somercotes Dental',
		location: 'Derbyshire',
		image: 'somercotes.jpg',
		href: 'somercotes-dental',
	},
	{
		name: 'Tollgate Dental',
		location: 'Nuneaton',
		image: 'tollgate.png',
		href: 'tollgate-dental',
	},
	{
		name: 'Normanton Road Dental',
		location: 'Derby',
		image: 'normanton.png',
		href: 'normanton-road-dental',
	},
	{
		name: 'Manor Park Family Dental Centre',
		location: 'Sheffield',
		image: 'manor-park.jpg',
		href: 'manor-park',
	},
] as const;
