export const practices = [
	{
		name: 'Abbeydale Road Family Dental Centre',
		location: 'Sheffield',
		image: 'abbeydale-road.jpg',
		href: 'abbeydale-road-family-dental-centre',
	},
	{
		name: 'Seven Dental',
		location: 'Nottingham',
		image: 'seven-dental.jpg',
		href: 'seven-dental',
	},
	{
		name: 'Anstey Family Dental Centre',
		location: 'Leicester',
		image: 'anstey.jpg',
		href: 'anstey-family-dental-centre',
	},
	{
		name: 'Market Place Dental Care',
		location: 'Mansfield',
		image: 'marketplace.png',
		href: 'market-place-dental-care',
	},
	{
		name: 'Clay Cross Family Dental Centre',
		location: 'Chesterfield',
		image: 'clay-cross.jpg',
		href: 'clay-cross-family-dental-centre',
	},
	{
		name: 'Dalton Dental Care',
		location: 'Rotherham',
		image: 'dalton.png',
		href: 'dalton-dental-care',
	},
	{
		name: 'South Elmsall Family Dental Centre',
		location: 'Pontefract',
		image: 'south-elmsall.jpg',
		href: 'south-elmsall-family-dental-centre',
	},
	{
		name: 'Hillsborough Family Dental Centre',
		location: 'Sheffield',
		image: 'hillsborough.jpg',
		href: 'hillsborough-family-dental-centre',
	},
	{
		name: 'Hoyland Road',
		location: 'Barnsley',
		image: 'hoyland.png',
		href: 'hoyland-road-dental',
	},
	{
		name: 'Portland Road Dental',
		location: 'Nottingham',
		image: 'portland.png',
		href: 'portland-road-dental',
	},
	{
		name: 'Sileby Dental',
		location: 'Loughborough',
		image: 'sileby.png',
		href: 'sileby-dental',
	},
	{
		name: 'Sneinton Family Dental',
		location: 'Nottingham',
		image: 'sneinton.jpg',
		href: 'sneinton-family-dental',
	},
	{
		name: 'Somercotes Dental',
		location: 'Alfreton',
		image: 'somercotes.png',
		href: 'somercotes-dental',
	},
	{
		name: 'Tollgate Dental',
		location: 'Nuneaton',
		image: 'tollgate.png',
		href: 'tollgate-dental',
	},
	{
		name: 'Normanton Road Dental',
		location: 'Sheffield',
		image: 'normanton.png',
		href: 'normanton-road-dental',
	},
] as const;
