export const practices = [
	{
		image: 'abbeydale-road',
		href: 'abbeydale-road-family-dental-centre',
		name: 'Abbeydale Road Family Dental Centre',
		address: '4-6 Abbeydale Rd, Highfield, Sheffield S7 1FD',
		phone: '0114 255 4433',
	},
	{
		image: 'seven-dental',
		href: 'seven-dental',
		name: 'Seven Dental',
		address: '69-75 Radford Road, Hyson Green, Nottingham NG7 5DR',
		phone: '0115 970 0007',
	},
	{
		image: 'anstey',
		href: 'anstey-family-dental-centre',
		name: 'Anstey Family Dental Centre',
		address: '9 Bradgate Rd, Anstey, Leicester LE7 7AB',
		phone: '0116 236 2534',
	},
	{
		image: 'marketplace',
		href: 'market-place-dental-care',
		name: 'Market Place Dental Care',
		address: 'Crown and Anchor, 3 Exchange Row, Mansfield NG18 1JU',
		phone: '01623 634287',
	},
	{
		image: 'clay-cross',
		href: 'clay-cross-family-dental-centre',
		name: 'Clay Cross Family Dental Centre',
		address: '69 Holmgate Rd, Clay Cross, Chesterfield S45 9PG',
		phone: '01246 863185',
	},
	{
		image: 'dalton',
		href: 'dalton-dental-care',
		name: 'Dalton Dental Care',
		address: '5 Doncaster Rd, Rotherham S65 3ET',
		phone: '01709 855999',
	},
	{
		image: 'south-elmsall',
		href: 'south-elmsall-family-dental-centre',
		name: 'South Elmsall Family Dental Centre',
		address: '51 Barnsley Rd, South Elmsall, Pontefract WF9 2SA',
		phone: '01977 645002',
	},
	{
		image: 'hillsborough',
		href: 'hillsborough-family-dental-centre',
		name: 'Hillsborough Family Dental Centre',
		address: '1 Victor St, Sheffield S6 2SA',
		phone: '0114 2344810',
	},
	{
		image: 'hoyland',
		href: 'hoyland-road-dental',
		name: 'Hoyland Family Dental Centre',
		address: '17 Milton Rd, Hoyland, Barnsley S74 9AU',
		phone: '01226 748404',
	},
	{
		image: 'portland',
		href: 'portland-road-dental',
		name: 'Portland Road Family Dental Centre',
		address: '7 Portland Rd, Hucknall, Nottingham NG15 7SL',
		phone: '0115 9632525',
	},
	{
		image: 'sileby',
		href: 'sileby-dental',
		name: 'Sileby Dental',
		address: '4 High St, Sileby, Loughborough LE12 7RX',
		phone: '01509 814565',
	},
	{
		name: 'The Sneinton Family Dental Centre',
		image: 'sneinton',
		href: 'sneinton-family-dental',
		address: '2 Colwick Rd, Sneinton, Nottingham NG2 4BU',
		phone: '0115 9242526',
	},
	{
		image: 'somercotes',
		href: 'somercotes-dental',
		name: 'Somercotes Dental Practice',
		address: '350-352 Lower Somercotes, Somercotes, Alfreton DE55 4LP',
		phone: '01773 609543',
	},
	{
		image: 'tollgate',
		href: 'tollgate-dental',
		name: 'Tollgate Dental Practice',
		address: '39 Barton Rd, Barlestone, Nuneaton CV13 0EU',
		phone: '01455 291067',
	},
	{
		image: 'normanton',
		href: 'normanton-road-dental',
		name: 'Normanton Family Dental Centre',
		address: '254 Normanton Rd, Derby DE23 6WD',
		phone: '01332 242526',
	},
	{
		image: 'manor-park',
		href: 'manor-park',
		name: 'Manor Park Dental Practice',
		address: '1A Motehall Rd, Sheffield S2 1RA',
		phone: '0114 2392985',
	},
] as const;
